title: Products
template: product
layout: layout
taxonomies:
  - type
  - tags
  - vendor
  - collections
revisions: false
route: '/products/{slug}'
sort_dir: asc
date: true
date_behavior:
  past: public
  future: private
