name: Bundle Release Assets

on:
  workflow_dispatch:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    if: github.event.release.draft == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Use Node.js 23.3.0
        uses: actions/setup-node@v4
        with:
          node-version: 23.3.0

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install node dependencies
        run: npm ci

      - name: Build release assets
        run: npm run build

      - name: Create zip
        run: tar -czvf dist.tar.gz dist

      - name: Upload dist zip to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.event.release.tag_name }}" dist.tar.gz --clobber

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit "${{ github.event.release.tag_name }}" --draft=false
